# version: "1"
# services:
#   auth_service:
#     build: ./auth_service
#     ports:
#       - "3000:3000"
#     depends_on:
#       - database
#     volumes:
#       - auth_data:/app/data  # Volume for the auth_service container data

#   database:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - database_data:/data/db  # Volume for the database container data

#   service1:
#     build: ./service_first
#     ports:
#       - "4000:4000"
#     depends_on:
#       - database1
#     volumes:
#       - service1_data:/app/data  # Volume for the service1 container data

#   database1:
#     image: mongo
#     ports:
#       - "27018:27017"
#     volumes:
#       - database1_data:/data/db  # Volume for the database1 container data
  
#   service2:
#     build: ./service_second
#     ports:
#       - "5000:5000"
#     depends_on:
#       - database2
#     volumes:
#       - service2_data:/app/data  # Volume for the service2 container data

#   database2:
#     image: mongo
#     ports:
#       - "27019:27017"
#     volumes:
#       - database2_data:/data/db  # Volume for the database2 container data

#   service3:
#     build: ./service_third
#     ports:
#       - "6000:6000"
#     depends_on:
#       - database3
#     volumes:
#       - service3_data:/app/data  # Volume for the service3 container data

#   database3:
#     image: mongo
#     ports:
#       - "27020:27017"
#     volumes:
#       - database3_data:/data/db  # Volume for the database3 container data

# volumes:
#   auth_data: {}
#   database_data: {}
#   service1_data: {}
#   database1_data: {}
#   service2_data: {}
#   database2_data: {}
#   service3_data: {}
#   database3_data: {}
version: "3.8"  # Updated to a more recent version of Docker Compose

services:
  auth_service:
    build: ./auth_service
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/auth_db  # Use environment variables to configure the MongoDB URI for auth_service
    volumes:
      - auth_data:/app/data  # Volume for the auth_service container data

  service1:
    build: ./service_first
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/service1_db  # Use environment variables to configure the MongoDB URI for service1
    volumes:
      - service1_data:/app/data  # Volume for the service1 container data

  service2:
    build: ./service_second
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/service2_db  # Use environment variables to configure the MongoDB URI for service2
    volumes:
      - service2_data:/app/data  # Volume for the service2 container data

  service3:
    build: ./service_third
    ports:
      - "6000:6000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/service3_db  # Use environment variables to configure the MongoDB URI for service3
    volumes:
      - service3_data:/app/data  # Volume for the service3 container data

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - database_data:/data/db  # Volume for the database container data

volumes:
  auth_data: {}
  service1_data: {}
  service2_data: {}
  service3_data: {}
  database_data: {}