version: "1"
services:
  auth_service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - my_database_data:/app/data   # Adjust the path according to your app's requirements

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my_database_data:/data/db

volumes:
  my_database_data:

